[package]
authors     = ["Xavier Lau <c.estlavie@icloud.com>"]
categories  = [
	"encoding",
	"no-std",
]
description = "array-bytes"
edition     = "2018"
homepage    = "https://array-bytes.l2ust.world"
keywords    = [
	"array",
	"bytes",
	"hex",
	"no-std",
	"serde",
]
license     = "GPL-3.0"
name        = "array-bytes"
readme      = "README.md"
repository  = "https://github.com/l2ust/array-bytes"
version     = "1.3.3"

[badges]
maintenance = { status = "actively-developed" }

[dependencies]
serde = { version = "1.0.126", optional = true, default-features = false }
# thiserror = { version = "1.0.25" }
